const { chromium } = require('playwright');
const assert = require('node:assert/strict');
require('node:fs').mkdirSync('/tmp/cerritos-validation',{recursive:true});
(async () => {
  const browser = await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE_PATH || undefined,args:["--no-sandbox"]});
  const context = await browser.newContext({viewport:{width:1440,height:1100},timezoneId:'America/Bogota',colorScheme:'light'});
  const page = await context.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.CERRITOS_TEST_URL || 'http://127.0.0.1:5173');
  await page.getByRole('heading',{name:'Tu comunidad, en orden.'}).waitFor();
  await page.evaluate(()=>document.fonts.ready);
  await page.screenshot({path:'/tmp/cerritos-validation/desktop.png',fullPage:true});
  assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  const themeSwitch=page.getByRole('switch',{name:'Modo oscuro'});
  await themeSwitch.focus();
  await page.keyboard.press('Space');
  assert.equal(await themeSwitch.getAttribute('aria-checked'),'true');
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.screenshot({path:'/tmp/cerritos-validation/desktop-dark.png',fullPage:true});
  await page.getByRole('button',{name:'Nueva reserva',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByRole('button',{name:'Zona BBQ',exact:true}).click();
  await dialog.getByLabel('Nombre del residente').fill('Residente de prueba');
  await dialog.getByLabel('Casa o apartamento').fill('Casa 99');
  await dialog.getByLabel('Hora de entrada').fill('12:30');
  await dialog.getByLabel('Hora de salida').fill('14:00');
  await dialog.getByRole('button',{name:'Confirmar reserva'}).click();
  await dialog.getByRole('alert').filter({hasText:'ya está reservada'}).waitFor();
  await dialog.getByLabel('Hora de entrada').fill('19:00');
  await dialog.getByLabel('Hora de salida').fill('20:00');
  await dialog.getByLabel('Observaciones').fill('Reserva de prueba automatizada');
  await dialog.getByRole('button',{name:'Confirmar reserva'}).click();
  await page.getByRole('status').filter({hasText:'Reserva creada correctamente'}).waitFor();
  await page.reload();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  assert.equal(await page.getByRole('switch',{name:'Modo oscuro'}).getAttribute('aria-checked'),'true');
  await page.getByRole('button').filter({hasText:'Residente de prueba'}).click();
  await dialog.getByText('Reserva de prueba automatizada').waitFor();
  await dialog.getByRole('button',{name:'Cancelar reserva',exact:true}).click();
  await dialog.getByRole('button',{name:'Sí, cancelar reserva'}).click();
  assert.equal(await page.getByRole('button').filter({hasText:'Residente de prueba'}).count(),0);
  await page.getByRole('navigation',{name:'Navegación principal'}).getByRole('button',{name:'Vehículos',exact:true}).click();
  await page.getByRole('button',{name:'Registrar ingreso',exact:true}).click();
  await dialog.getByLabel('Placa del vehículo').fill('xyz987');
  await dialog.getByLabel('Nombre del conductor').fill('Conductor de prueba');
  await dialog.getByLabel('Vivienda de destino').fill('Casa 99');
  await dialog.getByLabel('Novedades al ingreso').fill('Espejo derecho rayado antes del ingreso');
  await dialog.getByRole('button',{name:'Registrar ingreso',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Ingreso de XYZ987 registrado'}).waitFor();
  await page.getByRole('button',{name:'Registrar ingreso',exact:true}).click();
  await dialog.getByLabel('Placa del vehículo').fill('xyz987');
  await dialog.getByLabel('Nombre del conductor').fill('Conductor de prueba');
  await dialog.getByLabel('Vivienda de destino').fill('Casa 99');
  await dialog.getByRole('button',{name:'Registrar ingreso',exact:true}).click();
  await dialog.getByRole('alert').filter({hasText:'ingreso activo'}).waitFor();
  await dialog.getByRole('button',{name:'Cerrar',exact:true}).click();
  await page.locator('.vehicle-card').filter({hasText:'XYZ987'}).getByRole('button',{name:'Registrar salida'}).click();
  assert.equal(await page.locator('.vehicle-card').filter({hasText:'XYZ987'}).count(),0);
  await page.getByRole('button',{name:'Historial',exact:true}).click();
  await page.locator('.vehicle-card').filter({hasText:'XYZ987'}).getByText('Salida registrada').waitFor();
  await page.getByRole('navigation',{name:'Navegación principal'}).getByRole('button',{name:/Novedades/}).click();
  await page.locator('.incident-card').filter({hasText:'XYZ987'}).getByText('Espejo derecho rayado antes del ingreso').waitFor();
  await page.locator('.incident-card').filter({hasText:'XYZ987'}).getByRole('button',{name:'Marcar como resuelta'}).click();
  await page.getByRole('button',{name:'Resueltas',exact:true}).click();
  await page.locator('.incident-card').filter({hasText:'XYZ987'}).getByText('Resuelta',{exact:true}).waitFor();
  await page.getByRole('navigation',{name:'Navegación principal'}).getByRole('button',{name:'Administración',exact:true}).click();
  await page.getByPlaceholder('Buscar residente, vivienda o zona').fill('Residente de prueba');
  await page.locator('tbody tr').getByText('Cancelada',{exact:true}).waitFor();
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar reservas'}).click();const download=await downloadPromise;
  await download.saveAs('/tmp/cerritos-validation/reservas.csv');
  const fs=require('node:fs');const csv=fs.readFileSync('/tmp/cerritos-validation/reservas.csv','utf8');
  assert.ok(csv.includes('Residente de prueba')&&csv.includes('Cancelada'));
  console.log('PASS: conflict detection, create reservation, persistence, cancellation, vehicle entry/duplicate/exit, linked incident/resolution, admin search and CSV export');
  await context.close();
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1,hasTouch:true,timezoneId:'America/Bogota',colorScheme:'dark'});
  const m=await mobile.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto(process.env.CERRITOS_TEST_URL || 'http://127.0.0.1:5173');
  await m.evaluate(()=>document.fonts.ready);
  assert.equal(await m.locator('html').getAttribute('data-theme'),'dark');
  await m.screenshot({path:'/tmp/cerritos-validation/mobile-dark.png',fullPage:true});
  await m.emulateMedia({colorScheme:'light'});
  await m.waitForFunction(()=>document.documentElement.dataset.theme==='light');
  await m.screenshot({path:'/tmp/cerritos-validation/mobile.png',fullPage:true});
  await m.getByRole('switch',{name:'Modo oscuro'}).click();
  await m.reload();
  assert.equal(await m.locator('html').getAttribute('data-theme'),'dark');
  for (const name of ['Reservas','Vehículos','Novedades','Admin','Inicio']) {
    await m.getByRole('navigation',{name:'Navegación móvil'}).getByRole('button',{name,exact:true}).click();
    assert.ok(await m.evaluate(()=>document.documentElement.scrollWidth<=390 && window.innerWidth===390),`overflow on ${name}`);
  }
  await m.getByRole('button',{name:'Nueva reserva',exact:true}).click();
  assert.ok(await m.getByRole('dialog').isVisible());
  await m.screenshot({path:'/tmp/cerritos-validation/mobile-form.png',fullPage:true});
  await m.getByRole('dialog').getByRole('button',{name:'Cerrar',exact:true}).click();
  console.log('PASS: system theme, keyboard toggle, saved preference after reload, mobile toggle');
  console.log('PASS: all five mobile pages have no horizontal overflow; mobile reservation dialog opens and closes');
  assert.deepEqual(errors,[]); console.log('PASS: no browser runtime errors');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
