import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownLeft, ArrowRight, ArrowUpRight, Building2, CalendarDays, Car, Check, CheckCheck, ChevronLeft, ChevronRight, Clock3, Download, Dumbbell, Flame, HelpCircle, House, LayoutDashboard, Leaf, LogOut, Menu, MessageSquareText, Plus, Search, ShieldCheck, SlidersHorizontal, Users, X } from 'lucide-react';
import { areas, loadData, reservationError, shiftDate, STORAGE_KEY, today, vehicleError, type Area, type Data, type Reservation, type Vehicle } from './domain';

type Page = 'Inicio' | 'Reservas' | 'Vehículos' | 'Novedades' | 'Administración';
type Modal = {type:'reservation'} | {type:'vehicle'} | {type:'incident';vehicle?:Vehicle} | {type:'detail';reservation:Reservation} | {type:'help'} | null;
const nav = [{name:'Inicio',icon:LayoutDashboard},{name:'Reservas',icon:CalendarDays},{name:'Vehículos',icon:Car},{name:'Novedades',icon:MessageSquareText},{name:'Administración',icon:Users}] as const;
const areaClass = (area: Area) => area === 'Salón social' ? 'social' : area === 'Gimnasio' ? 'gym' : 'bbq';
const AreaIcon = ({area,size=20}: {area: Area;size?:number}) => area === 'Salón social' ? <Building2 size={size}/> : area === 'Gimnasio' ? <Dumbbell size={size}/> : <Flame size={size}/>;
const prettyDate = (date: string, opts: Intl.DateTimeFormatOptions = {day:'numeric',month:'long'}) => new Date(`${date}T12:00:00`).toLocaleDateString('es-CO',opts);
const time = (iso: string) => new Date(iso).toLocaleTimeString('es-CO',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'America/Bogota'});
const initials = (name: string) => name.split(' ').slice(0,2).map(n=>n[0]).join('');
const id = () => crypto.randomUUID();

function Dialog({title,subtitle,onClose,children}: {title:string;subtitle:string;onClose:()=>void;children:ReactNode}) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(()=>{ const d=ref.current!; d.showModal(); return ()=>d.close(); },[]);
  return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-labelledby="dialog-title"><div className="dialog-heading"><div><span className="eyebrow">CERRITOS HOME</span><h2 id="dialog-title">{title}</h2><p>{subtitle}</p></div><button className="icon-button" aria-label="Cerrar" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;
}

export default function App() {
  const [initial] = useState(loadData);
  const [data,setData] = useState<Data>(initial.data);
  const [storageError,setStorageError] = useState(initial.error);
  const [page,setPage] = useState<Page>('Inicio');
  const [date,setDate] = useState(today());
  const [area,setArea] = useState<Area|'Todas'>('Todas');
  const [search,setSearch] = useState('');
  const [vehicleFilter,setVehicleFilter] = useState('Dentro del conjunto');
  const [incidentFilter,setIncidentFilter] = useState('Pendientes');
  const [modal,setModal] = useState<Modal>(null);
  const [error,setError] = useState('');
  const [toast,setToast] = useState('');
  const [mobileNav,setMobileNav] = useState(false);
  const [confirmCancel,setConfirmCancel] = useState(false);
  const [formArea,setFormArea] = useState<Area>('Salón social');
  const [showCancelled,setShowCancelled] = useState(false);
  useEffect(()=>{ if(initial.error) return; try {localStorage.setItem(STORAGE_KEY,JSON.stringify(data));setStorageError('');}catch {setStorageError('No se pudieron guardar los cambios en este dispositivo. No cierres la página hasta liberar espacio en el navegador.');} },[data,initial.error]);
  useEffect(()=>{ if(!toast)return; const timer=setTimeout(()=>setToast(''),4500);return ()=>clearTimeout(timer); },[toast]);
  const go = (next: Page) => {setPage(next);setSearch('');setMobileNav(false);};
  const open = (m:Modal) => {setError('');setConfirmCancel(false);setModal(m);};
  const notify = (message:string) => {setModal(null);setToast(message);};
  const matches = (...values:string[]) => values.join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase());
  const activeReservations = data.reservations.filter(r=>!r.cancelled);
  const dayReservations = activeReservations.filter(r=>r.date===date).sort((a,b)=>a.start.localeCompare(b.start));
  const visibleReservations = data.reservations.filter(r=>r.date===date && (showCancelled || !r.cancelled) && (area==='Todas'||r.area===area) && matches(r.resident,r.unit,r.area)).sort((a,b)=>a.start.localeCompare(b.start));
  const insideVehicles = data.vehicles.filter(v=>!v.exited);
  const pendingIncidents = data.incidents.filter(i=>!i.resolved);
  const activeToday = activeReservations.filter(r=>r.date===today());
  const monday = shiftDate(date,-((new Date(`${date}T12:00:00`).getDay()+6)%7));
  const saveReservation = (e:FormEvent<HTMLFormElement>) => {
    e.preventDefault(); const f=new FormData(e.currentTarget); const r={resident:String(f.get('resident')).trim(),unit:String(f.get('unit')).trim(),area:formArea,date:String(f.get('date')),start:String(f.get('start')),end:String(f.get('end')),notes:String(f.get('notes')).trim()};
    const problem=reservationError(r,data.reservations);if(problem){setError(problem);return;}
    setData(d=>({...d,reservations:[...d.reservations,{...r,id:id(),cancelled:false}]}));setDate(r.date);setArea('Todas');setSearch('');notify('Reserva creada correctamente');
  };
  const saveVehicle = (e:FormEvent<HTMLFormElement>) => {
    e.preventDefault();const f=new FormData(e.currentTarget);const plate=String(f.get('plate')).trim().toUpperCase();const driver=String(f.get('driver')).trim();const unit=String(f.get('unit')).trim();
    const problem=vehicleError(plate,driver,unit,data.vehicles);if(problem){setError(problem);return;}
    const vehicleId=id(); const note=String(f.get('notes')).trim();const created=new Date().toISOString();
    setData(d=>({...d,vehicles:[{id:vehicleId,plate,driver,unit,reason:String(f.get('reason')),entered:created,exited:null},...d.vehicles],incidents:note?[{id:id(),title:`Novedad de ingreso · ${plate}`,description:note,category:'Vehículo',vehicleId,created,resolved:false},...d.incidents]:d.incidents}));
    setVehicleFilter('Dentro del conjunto');setSearch('');notify(`Ingreso de ${plate} registrado`);
  };
  const saveIncident = (e:FormEvent<HTMLFormElement>) => {
    e.preventDefault(); const f=new FormData(e.currentTarget);const title=String(f.get('title')).trim();const description=String(f.get('description')).trim();
    if(!title||!description){setError('Completa el título y la descripción.');return;}
    setData(d=>({...d,incidents:[{id:id(),title,description,category:String(f.get('category')),vehicleId:modal?.type==='incident'?modal.vehicle?.id:undefined,created:new Date().toISOString(),resolved:false},...d.incidents]}));setIncidentFilter('Pendientes');setSearch('');notify('Novedad registrada correctamente');
  };
  const exportReservations = () => {
    const cell = (value:string) => `"${(/^[=+\-@\t\r]/.test(value)?"'":'')+value.replaceAll('"','""')}"`;
    const rows=[['Fecha','Zona','Residente','Vivienda','Entrada','Salida','Estado','Observaciones'],...data.reservations.filter(r=>matches(r.resident,r.unit,r.area)).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)).map(r=>[r.date,r.area,r.resident,r.unit,r.start,r.end,r.cancelled?'Cancelada':'Confirmada',r.notes])];
    const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`reservas-cerritos-${today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setToast('Reporte de reservas exportado');
  };
  const ReservationRow = ({r}: {r:Reservation}) => <button className={`reservation-row ${r.cancelled?'cancelled':''}`} onClick={()=>open({type:'detail',reservation:r})}><div className="time-cell"><strong>{r.start}</strong><span>{r.end}</span></div><span className={`area-icon ${areaClass(r.area)}`}><AreaIcon area={r.area}/></span><div className="reservation-main"><strong>{r.area}</strong><span>{r.resident} <span className="dot">·</span> {r.unit}</span></div><span className={`status ${r.cancelled?'muted':'confirmed'}`}>{r.cancelled?'Cancelada':'Confirmada'}</span><ChevronRight size={17} className="row-chevron"/></button>;
  const Empty = ({text,detail}: {text:string;detail:string}) => <div className="empty"><CalendarDays size={30}/><h3>{text}</h3><p>{detail}</p></div>;
  return <div className="app-shell">
    {mobileNav&&<button className="nav-scrim" aria-label="Cerrar menú" onClick={()=>setMobileNav(false)}/>}
    <aside className={`sidebar ${mobileNav?'is-open':''}`}>
      <a className="brand" href="#" onClick={e=>{e.preventDefault();go('Inicio');}}><img src="/icon.svg" alt=""/><div>Cerritos<span>HOME</span></div></a>
      <div className="community-label">ESPACIOS QUE NOS UNEN</div>
      <div className="workspace-label">MI CONJUNTO</div>
      <nav aria-label="Navegación principal">{nav.map(({name,icon:Icon})=><button key={name} onClick={()=>go(name)} className={page===name?'active':''}><Icon size={20}/><span>{name}</span>{name==='Novedades'&&pendingIncidents.length>0&&<span className="nav-count">{pendingIncidents.length}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="community-card"><span className="community-symbol"><Leaf size={24}/></span><strong>Una comunidad mejor,<br/>comienza con nosotros.</strong><p>Cuidamos lo que compartimos.</p></div><button className="help-button" onClick={()=>open({type:'help'})}><HelpCircle size={19}/>Guía de uso<ArrowUpRight size={15}/></button><div className="sidebar-footer"><span className="online-dot"/>Espacio de demostración<span>v0.1</span></div></div>
    </aside>
    <div className="main-shell">
      <header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Abrir menú" onClick={()=>setMobileNav(true)}><Menu size={22}/></button><span>Cerritos Home</span><ChevronRight size={14}/><strong>{page}</strong></div><div className="topbar-right"><span className="date-top"><CalendarDays size={16}/>{prettyDate(today(),{day:'numeric',month:'short',year:'numeric'})}</span><span className="top-divider"/><div className="profile-avatar">CH</div><div className="profile-text"><strong>Equipo Cerritos</strong><span>Portería y administración</span></div></div></header>
      <main>
        <div className="page-heading"><div><div className="eyebrow">{page==='Inicio'?'TODO EN SU LUGAR':page==='Administración'?'UNA VISIÓN COMPLETA':'GESTIÓN DE LA COMUNIDAD'}</div><h1>{page==='Inicio'?'Tu comunidad, en orden.':page==='Vehículos'?'Control de vehículos':page==='Novedades'?'Novedades del conjunto':page==='Administración'?'Panel de administración':'Reserva los buenos momentos.'}</h1><p>{page==='Inicio'?'Un nuevo día para cuidar lo que compartimos.':page==='Reservas'?'Organiza los espacios y haz lugar para disfrutar.':page==='Vehículos'?'Cada ingreso registrado. Cada visita bajo control.':page==='Novedades'?'Registra, da seguimiento y mantén informado al equipo.':'Todas las reservas y la actividad del conjunto, en un solo lugar.'}</p></div><button className="button primary" onClick={()=>page==='Administración'?exportReservations():open({type:page==='Vehículos'?'vehicle':page==='Novedades'?'incident':'reservation'})}>{page==='Administración'?<Download size={18}/>:<Plus size={19}/>}<span>{page==='Administración'?'Exportar reservas':page==='Vehículos'?'Registrar ingreso':page==='Novedades'?'Nueva novedad':'Nueva reserva'}</span></button></div>
        <div className="demo-banner"><span><span className="demo-dot"/>Modo demostración</span><p>Datos de ejemplo y cambios guardados solo en este navegador.</p></div>
        {storageError&&<div className="error global-error" role="alert">{storageError}</div>}
        {(page==='Inicio'||page==='Administración')&&<div className="stats-grid">
          {[{label:'Reservas para hoy',value:activeToday.length,icon:CalendarDays,color:'green',foot:'En nuestros espacios comunes',target:'Reservas'},{label:'Vehículos en el conjunto',value:insideVehicles.length,icon:Car,color:'blue',foot:'Ingresos activos en este momento',target:'Vehículos'},{label:'Novedades pendientes',value:pendingIncidents.length,icon:MessageSquareText,color:'orange',foot:'Por revisar con el equipo',target:'Novedades'},{label:'Espacios comunes',value:3,icon:Building2,color:'purple',foot:'Para disfrutar en comunidad',target:'Reservas'}].map(s=><button key={s.label} className="stat-card" onClick={()=>{go(s.target as Page);setDate(today());setSearch('');}}><div className="stat-top"><span>{s.label}</span><span className={`stat-icon ${s.color}`}><s.icon size={19}/></span></div><div className="stat-number">{String(s.value).padStart(2,'0')}<ArrowUpRight size={19}/></div><div className="stat-foot">{s.foot}</div></button>)}
        </div>}
        {(page==='Inicio'||page==='Reservas')&&<div className="dashboard-grid"><div className="left-column">
          <section className="panel agenda"><div className="panel-heading"><div><h2>Agenda de reservas <span className="count-pill">{dayReservations.length}</span></h2><p>Los planes de nuestra comunidad.</p></div><div className="date-controls"><button className="icon-button" aria-label="Semana anterior" onClick={()=>setDate(shiftDate(date,-7))}><ChevronLeft size={17}/></button><span>{prettyDate(date,{month:'long',year:'numeric'})}</span><button className="icon-button" aria-label="Semana siguiente" onClick={()=>setDate(shiftDate(date,7))}><ChevronRight size={17}/></button></div></div>
            <div className="week-strip">{Array.from({length:7},(_,i)=>shiftDate(monday,i)).map(d=><button key={d} aria-pressed={date===d} className={`day ${date===d?'selected':''}`} onClick={()=>setDate(d)}><span>{prettyDate(d,{weekday:'short'}).replace('.','')}</span><strong>{prettyDate(d,{day:'2-digit'})}</strong><i className={activeReservations.some(r=>r.date===d)?'has-reservations':''}/></button>)}</div>
            <div className="agenda-tools"><div className="tabs area-tabs">{(['Todas',...areas] as const).map(a=><button className={area===a?'selected':''} key={a} onClick={()=>setArea(a)}>{a==='Todas'?'Todos los espacios':a}</button>)}</div></div>
            {page==='Reservas'&&<div className="reservation-filters"><label className="search-input"><Search size={17}/><input placeholder="Buscar residente o vivienda" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="checkbox-label"><input type="checkbox" checked={showCancelled} onChange={e=>setShowCancelled(e.target.checked)}/>Ver canceladas</label></div>}
            <div className="list-label"><span>{date===today()?'HOY':prettyDate(date,{weekday:'long'}).toUpperCase()} <span>· {prettyDate(date)}</span></span><label className="date-picker"><CalendarDays size={14}/><input aria-label="Elegir fecha de agenda" type="date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label></div>
            <div className="reservation-list">{visibleReservations.length?visibleReservations.map(r=><ReservationRow key={r.id} r={r}/>):<Empty text="Un espacio para nuevos planes" detail="No hay reservas con estos filtros. Crea una reserva o selecciona otra fecha."/>}</div>
            <div className="agenda-footer"><span><span className="small-dot"/>{dayReservations.length} reservas confirmadas</span><button className="text-button" onClick={()=>{setDate(today());setArea('Todas');setSearch('');}}>Volver a hoy<ArrowRight size={15}/></button></div>
          </section>
          <section className="spaces-section"><div className="section-title"><h2>Espacios para compartir</h2><span>Elige tu próximo plan</span></div><div className="spaces-grid">{areas.map((a,i)=><button className={`space-card ${areaClass(a)}`} key={a} onClick={()=>{setFormArea(a);open({type:'reservation'});}}><div className="space-art"><div className="art-circle"/><AreaIcon area={a} size={52}/><span className="space-book"><Plus size={15}/>Reservar</span></div><div className="space-info"><strong>{a}</strong><span>{['Celebremos juntos','Tiempo para ti','Sabores y buenos momentos'][i]}</span></div></button>)}</div></section>
        </div><aside className="right-column">
          <section className="welcome-card"><div className="welcome-tag"><Leaf size={14}/>VIVIR BIEN, JUNTOS</div><h2>Pequeños cuidados.<br/>Grandes momentos.</h2><p>Cada espacio, cada visita y cada detalle hacen de Cerritos nuestro hogar.</p><div className="welcome-landscape"><span className="sun"/><span className="hill hill-one"/><span className="hill hill-two"/><House className="landscape-house" size={74} strokeWidth={1}/><span className="landscape-tree"><Leaf size={63} strokeWidth={1}/></span></div><span className="welcome-caption">BIENVENIDO A CASA</span></section>
          <section className="panel quick-actions"><h2>A un clic</h2><button onClick={()=>open({type:'vehicle'})}><span className="quick-icon blue"><Car size={20}/></span><span><strong>Registrar un vehículo</strong><small>Un ingreso seguro y organizado</small></span><ChevronRight size={17}/></button><button onClick={()=>open({type:'incident'})}><span className="quick-icon orange"><MessageSquareText size={20}/></span><span><strong>Reportar una novedad</strong><small>Los detalles también importan</small></span><ChevronRight size={17}/></button></section>
          <section className="panel latest"><div className="panel-heading"><h2>Por atender <span className="count-pill">{pendingIncidents.length}</span></h2><button className="text-button" onClick={()=>go('Novedades')}>Ver todo<ArrowRight size={14}/></button></div>{pendingIncidents.slice(0,2).map(i=><button className="latest-item" key={i.id} onClick={()=>go('Novedades')}><span className="incident-dot"/><span><strong>{i.title}</strong><small>{i.category} · {time(i.created)}</small></span></button>)}{!pendingIncidents.length&&<p className="all-good"><CheckCheck size={18}/>Todo al día. ¡Buen trabajo!</p>}</section>
        </aside></div>}
        {page==='Vehículos'&&<section className="panel management-panel"><div className="management-toolbar"><div className="tabs">{['Dentro del conjunto','Historial'].map(f=><button key={f} className={vehicleFilter===f?'selected':''} onClick={()=>setVehicleFilter(f)}>{f}{f==='Dentro del conjunto'&&<span className="count-pill">{insideVehicles.length}</span>}</button>)}</div><label className="search-input"><Search size={18}/><input placeholder="Buscar placa, conductor o vivienda" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="vehicle-list">{data.vehicles.filter(v=>(vehicleFilter==='Historial'||!v.exited)&&matches(v.plate,v.driver,v.unit)).map(v=><article className="vehicle-card" key={v.id}><div className="vehicle-card-main"><span className="vehicle-icon"><Car size={27}/></span><div><span className="plate">{v.plate}</span><h3>{v.driver}</h3><p>{v.unit} <span className="dot">·</span> {v.reason}</p></div><span className={`status ${v.exited?'muted':'confirmed'}`}>{v.exited?'Salida registrada':'En el conjunto'}</span></div><div className="vehicle-times"><span><ArrowDownLeft size={15}/>Ingreso: {new Date(v.entered).toLocaleDateString('es-CO',{timeZone:'America/Bogota'})}, {time(v.entered)}</span>{v.exited&&<span><ArrowUpRight size={15}/>Salida: {new Date(v.exited).toLocaleDateString('es-CO',{timeZone:'America/Bogota'})}, {time(v.exited)}</span>}</div><div className="vehicle-actions"><button className="text-button" onClick={()=>open({type:'incident',vehicle:v})}><MessageSquareText size={16}/>Registrar novedad</button>{!v.exited&&<button className="button secondary small" onClick={()=>{setData(d=>({...d,vehicles:d.vehicles.map(x=>x.id===v.id?{...x,exited:new Date().toISOString()}:x)}));setToast(`Salida de ${v.plate} registrada`);}}><LogOut size={15}/>Registrar salida</button>}</div></article>)}</div>{!data.vehicles.some(v=>(vehicleFilter==='Historial'||!v.exited)&&matches(v.plate,v.driver,v.unit))&&<Empty text="No hay vehículos para mostrar" detail="Los ingresos que registres aparecerán aquí."/>}</section>}
        {page==='Novedades'&&<section className="panel management-panel"><div className="management-toolbar"><div className="tabs">{['Pendientes','Resueltas','Todas'].map(f=><button className={incidentFilter===f?'selected':''} key={f} onClick={()=>setIncidentFilter(f)}>{f}</button>)}</div><label className="search-input"><Search size={18}/><input placeholder="Buscar una novedad" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="incidents-list">{data.incidents.filter(i=>(incidentFilter==='Todas'||(incidentFilter==='Resueltas'?i.resolved:!i.resolved))&&matches(i.title,i.description,i.category)).map(i=><article className="incident-card" key={i.id}><span className={`quick-icon ${i.resolved?'green':'orange'}`}>{i.resolved?<CheckCheck size={21}/>:<MessageSquareText size={21}/>}</span><div className="incident-body"><div className="incident-meta"><span>{i.category}</span><span>{new Date(i.created).toLocaleDateString('es-CO',{timeZone:'America/Bogota'})} · {time(i.created)}</span></div><h3>{i.title}</h3><p>{i.description}</p>{i.vehicleId&&<span className="vehicle-link"><Car size={14}/>{data.vehicles.find(v=>v.id===i.vehicleId)?.plate}</span>}<button className="text-button" onClick={()=>{setData(d=>({...d,incidents:d.incidents.map(x=>x.id===i.id?{...x,resolved:!x.resolved}:x)}));setToast(i.resolved?'Novedad reabierta':'Novedad marcada como resuelta');}}><Check size={16}/>{i.resolved?'Reabrir novedad':'Marcar como resuelta'}</button></div><span className={`status ${i.resolved?'confirmed':'pending'}`}>{i.resolved?'Resuelta':'Pendiente'}</span></article>)}</div>{!data.incidents.some(i=>(incidentFilter==='Todas'||(incidentFilter==='Resueltas'?i.resolved:!i.resolved))&&matches(i.title,i.description,i.category))&&<Empty text="Todo despejado por aquí" detail="No hay novedades que coincidan con este filtro."/>}</section>}
        {page==='Administración'&&<><div className="admin-notice"><ShieldCheck size={22}/><div><strong>Vista de supervisión</strong><p>Consulta todas las reservas y exporta el reporte para tu equipo. En esta demostración no hay autenticación ni permisos por usuario.</p></div></div><section className="panel"><div className="management-toolbar"><div><h2>Todas las reservas</h2><p className="subtle">Historial completo de los espacios comunes</p></div><label className="search-input"><Search size={18}/><input placeholder="Buscar residente, vivienda o zona" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="table-scroll"><table><thead><tr><th>Residente</th><th>Espacio</th><th>Fecha</th><th>Horario</th><th>Estado</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{data.reservations.filter(r=>matches(r.resident,r.unit,r.area)).sort((a,b)=>(b.date+b.start).localeCompare(a.date+a.start)).map(r=><tr key={r.id}><td><div className="resident-cell"><span className="avatar">{initials(r.resident)}</span><span><strong>{r.resident}</strong><small>{r.unit}</small></span></div></td><td><span className={`area-label ${areaClass(r.area)}`}><AreaIcon area={r.area} size={15}/>{r.area}</span></td><td>{prettyDate(r.date,{day:'numeric',month:'short',year:'numeric'})}</td><td>{r.start} – {r.end}</td><td><span className={`status ${r.cancelled?'muted':'confirmed'}`}>{r.cancelled?'Cancelada':'Confirmada'}</span></td><td><button className="text-button" aria-label={`Ver reserva de ${r.resident}`} onClick={()=>open({type:'detail',reservation:r})}>Ver<ChevronRight size={15}/></button></td></tr>)}</tbody></table></div>{!data.reservations.some(r=>matches(r.resident,r.unit,r.area))&&<Empty text="No se encontraron reservas" detail="Prueba con otro residente, vivienda o espacio."/>}</section></>}
        <footer className="main-footer"><span><Leaf size={13}/>Cerritos Home · Vivir bien, juntos.</span><span>Hecho para nuestra comunidad</span></footer>
      </main>
    </div>
    <nav className="mobile-bottom-nav" aria-label="Navegación móvil">{nav.map(({name,icon:Icon})=><button key={name} className={page===name?'active':''} onClick={()=>go(name)}><Icon size={20}/><span>{name==='Administración'?'Admin':name}</span></button>)}</nav>
    {toast&&<div className="toast" role="status"><CheckCheck size={19}/>{toast}<button aria-label="Cerrar notificación" onClick={()=>setToast('')}><X size={16}/></button></div>}
    {modal&&<Dialog title={modal.type==='reservation'?'Nueva reserva':modal.type==='vehicle'?'Registrar ingreso':modal.type==='incident'?'Registrar novedad':modal.type==='detail'?'Detalle de la reserva':'Bienvenido a Cerritos Home'} subtitle={modal.type==='reservation'?'Un espacio listo para compartir buenos momentos.':modal.type==='vehicle'?'Registra los datos de la visita al conjunto.':modal.type==='incident'?'Deja un registro claro para el equipo.':modal.type==='detail'?prettyDate(modal.reservation.date,{weekday:'long',day:'numeric',month:'long',year:'numeric'}):'Una guía rápida para tu día a día.'} onClose={()=>setModal(null)}>
      {modal.type==='reservation'&&<form onSubmit={saveReservation}><div className="form-areas">{areas.map(a=><button type="button" key={a} aria-pressed={formArea===a} className={`${areaClass(a)} ${formArea===a?'selected':''}`} onClick={()=>setFormArea(a)}><AreaIcon area={a}/>{a}</button>)}</div><div className="form-grid"><label className="full">Nombre del residente<input name="resident" placeholder="Ej. Valentina Gómez" required maxLength={90}/></label><label>Casa o apartamento<input name="unit" placeholder="Ej. Casa 24" required maxLength={40}/></label><label>Fecha<input name="date" type="date" min={today()} defaultValue={date<today()?today():date} required/></label><label>Hora de entrada<input name="start" type="time" defaultValue="09:00" required/></label><label>Hora de salida<input name="end" type="time" defaultValue="10:00" required/></label><label className="full">Observaciones <span className="optional">(opcional)</span><textarea name="notes" placeholder="Detalles que debemos tener en cuenta…" rows={3} maxLength={1000}/></label></div><p className="form-hint"><Clock3 size={15}/>Validaremos que el espacio no tenga otra reserva en ese horario.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={()=>setModal(null)}>Cancelar</button><button className="button primary" type="submit"><Check size={17}/>Confirmar reserva</button></div></form>}
      {modal.type==='vehicle'&&<form onSubmit={saveVehicle}><div className="form-grid"><label>Placa del vehículo<input name="plate" className="plate-input" placeholder="ABC123" required maxLength={10}/></label><label>Motivo de la visita<select name="reason"><option>Visita</option><option>Domicilio</option><option>Servicio técnico</option><option>Proveedor</option><option>Otro</option></select></label><label className="full">Nombre del conductor<input name="driver" placeholder="Nombre y apellido" required maxLength={90}/></label><label className="full">Vivienda de destino<input name="unit" placeholder="Ej. Casa 18" required maxLength={40}/></label><label className="full">Novedades al ingreso <span className="optional">(opcional)</span><textarea name="notes" placeholder="Estado del vehículo u observaciones de la visita…" rows={3} maxLength={1000}/></label></div><p className="form-hint"><Clock3 size={15}/>La fecha y hora de ingreso se registran automáticamente.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={()=>setModal(null)}>Cancelar</button><button type="submit" className="button primary"><ArrowDownLeft size={18}/>Registrar ingreso</button></div></form>}
      {modal.type==='incident'&&<form onSubmit={saveIncident}>{modal.vehicle&&<div className="linked-vehicle"><Car size={20}/>Vehículo {modal.vehicle.plate} · {modal.vehicle.driver}</div>}<div className="form-grid"><label className="full">Título<input name="title" placeholder="¿Qué ocurrió?" required maxLength={120}/></label><label className="full">Categoría<select name="category" defaultValue={modal.vehicle?'Vehículo':'General'}><option>General</option><option>Vehículo</option><option>Mantenimiento</option><option>Seguridad</option><option>Espacios comunes</option></select></label><label className="full">Descripción<textarea name="description" placeholder="Describe la situación y los detalles relevantes…" rows={4} required maxLength={2000}/></label></div>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button className="button secondary" type="button" onClick={()=>setModal(null)}>Cancelar</button><button className="button primary" type="submit">Guardar novedad<Check size={17}/></button></div></form>}
      {modal.type==='detail'&&<div className="reservation-detail"><div className={`detail-area ${areaClass(modal.reservation.area)}`}><AreaIcon area={modal.reservation.area} size={30}/><div><h3>{modal.reservation.area}</h3><p>{modal.reservation.start} – {modal.reservation.end}</p></div><span className={`status ${modal.reservation.cancelled?'muted':'confirmed'}`}>{modal.reservation.cancelled?'Cancelada':'Confirmada'}</span></div><dl><div><dt>Residente</dt><dd>{modal.reservation.resident}</dd></div><div><dt>Vivienda</dt><dd>{modal.reservation.unit}</dd></div><div className="full"><dt>Observaciones</dt><dd>{modal.reservation.notes||'Sin observaciones.'}</dd></div></dl>{!modal.reservation.cancelled&&<div className="cancellation"><p>{confirmCancel?'¿Confirmas la cancelación? El horario quedará disponible para otra reserva.':'Si los planes cambian, libera el espacio para otro vecino.'}</p><button className="button danger" onClick={()=>{if(!confirmCancel){setConfirmCancel(true);return;}const rid=modal.reservation.id;setData(d=>({...d,reservations:d.reservations.map(r=>r.id===rid?{...r,cancelled:true}:r)}));notify('Reserva cancelada. El horario está disponible.');}}>{confirmCancel?'Sí, cancelar reserva':'Cancelar reserva'}</button></div>}</div>}
      {modal.type==='help'&&<div className="help-content"><p><CalendarDays size={21}/><span><strong>Organiza las reservas</strong>Selecciona un espacio, un residente y un horario. Los cruces de horario se detectan automáticamente.</span></p><p><Car size={21}/><span><strong>Controla las visitas</strong>Registra la placa, el conductor y su destino. Al salir, marca la salida del vehículo.</span></p><p><MessageSquareText size={21}/><span><strong>Da seguimiento a las novedades</strong>Registra lo ocurrido y marca la novedad como resuelta cuando se atienda.</span></p><p><SlidersHorizontal size={21}/><span><strong>Consulta y exporta</strong>Administración muestra todas las reservas y permite descargarlas en CSV.</span></p><div className="help-note">Prototipo local para Android y web. Los cambios no se comparten entre dispositivos. Usa datos ficticios hasta contar con autenticación y almacenamiento seguro en un servidor. Horarios del conjunto: Colombia (UTC−5). La disponibilidad del gimnasio se gestiona por reserva exclusiva en esta versión.</div></div>}
    </Dialog>}
  </div>;
}
